### ISSUE TITLE
Add socket server sources

### ISSUE THREAD

**Issue by david4599** [Liinkiing/multiplayer-piano#10]
Can you add the Vue socket server sources?

I just want to make a backup in case your server become unavailable, so I can redirect requests on my own server and continue to have the multiplayer part working. It would be too bad to lose this feature.

Thanks.

**Comment by Liinkiing** [comment]
Hey, sure! I'll send you a link in your mail because the backend repo is private (due to poor code quality, don't judge :trollface:). It was made for a hobby project so the backend code may be fragile, use it as you want
